name: PR Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  notifications:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Discord channel
      env:
          TITLE: ${{ github.event.pull_request.title }}
      run: |
        curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"New PR: $TITLE\"}" ${{ vars.DISCORD_OSS_CHANNEL_WEBHOOK_URL}}
